web:
  build: .
  links:
    - db
  ports:
    - 80:80
  volumes:
    - ./www/html:/var/www/html

db:
  image: mysql:latest
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
  ports:
    - 8887:3306

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  ports:
    - 8080:80


mailhog:
  container_name: mailhog
  image: mailhog/mailhog
  restart: always
  ports:
    - 1025:1025 #smtp server
    - 8025:8025 #web ui
